### ISSUE TITLE
Canonical URL

### ISSUE THREAD

**Issue by ppKrauss** [datasets/co2-ppm#11]
Hi, this is the same dataset tham https://datahub.io/core/co2-ppm ?

Perhaps interesting to say "hello we are the same" at README, or to include a link as Country-codes in its Github-header, https://github.com/datasets/country-codes

**Comment by anuveyatsu** [comment]
@ppKrauss thanks for opening this issue! The GitHub header has a link to datahub page now. Closing as FIXED.
