### ISSUE TITLE
Auto updates on a regular basis

### ISSUE THREAD

**Issue by anuveyatsu** [datasets/co2-ppm#12]
As a User of this dataset, I want to have it auto-updated on regular basis, e.g. weekly, so that I can use it in my projects that will be always up-to-date.

**Comment by svetozarstojkovic** [comment]
This ticket has been resolved through: https://github.com/datopian/carbondoomsday/issues/2.

**Comment by jtpotato** [comment]
I have a [fork](https://github.com/jtpotato/co2-ppm) that uses GitHub Actions to automatically run the script on the 1st of each month.

The fork also includes other changes such as bypassing `make`

Should I open a PR or keep the feature downstream?

**Comment by rufuspollock** [comment]
@jtpotato that would be amazing and very welcome! We are happy to lose `make`!
